### ISSUE TITLE
能不能做个Emby的插件，想这个一样！！方便我们挂在网盘的用！

### ISSUE THREAD

**Issue by koboy9208** [CineMingle/CineMingle#3]
插件地址：https://github.com/metatube-community/jellyfin-plugin-metatube/releases

**Comment by CineMingle** [comment]
这个可以直接刮削🗾影片么？要是可以的话直接用？

**Comment by CineMingle** [comment]
1.2.0 发布应该支持115了。谢谢支持！

**Comment by koboy9208** [comment]
[+]Start at 2024-01-16 16:48:50
[+]Load Config file 'D:\guaxiao\CineMingle-1.2.0\config.ini'.
[+]Enable debug
[!]Enable soft link
[!]CmdLine: -L 1 -p V:\115
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 806, in <module>
    main(args)
  File "Movie_Data_Capture.py", line 710, in main
    movie_list = movie_lists(folder_path, regexstr)
  File "Movie_Data_Capture.py", line 399, in movie_lists
    for full_name in source.glob(r'**/*'):
  File "D:\guaxiao\CineMingle-1.2.0\python\lib\pathlib.py", line 1140, in glob
    for p in selector.select_from(self):
  File "D:\guaxiao\CineMingle-1.2.0\python\lib\pathlib.py", line 587, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "D:\guaxiao\CineMingle-1.2.0\python\lib\pathlib.py", line 534, in _select_from
    with scandir(parent_path) as scandir_it:
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'V:\\115\\JAV_output'

大佬这是啥问题
