### ISSUE TITLE
115虚拟盘刮削有错误

### ISSUE THREAD

**Issue by milanxiaotiejiang1** [CineMingle/CineMingle#8]
`PS E:\CineMingle> python Movie_Data_Capture.py -L 1 -p H:\115
[!]Set config override [common]link_mode=1  by cmd='common:link_mode=1'
[!]Set config override [common]source_folder=H:\115  by cmd='common:source_folder=H:\115'
[*]================= CineMingle =================
[*]                        1.2.0
[*]======================================================
[*] - Windows-10-10.0.22621-SP0
[*] - AMD64 - Python-3.8.10
[*]======================================================
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2024-01-14 13:48:07
[+]Load Config file 'E:\CineMingle\config.ini'.
[+]Enable debug
[!]Enable soft link
[!]CmdLine: -L 1 -p H:\115
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 805, in <module>
    main(args)
  File "Movie_Data_Capture.py", line 709, in main
    movie_list = movie_lists(folder_path, regexstr)
  File "Movie_Data_Capture.py", line 395, in movie_lists
    source = Path(source_folder).resolve()
  File "C:\Users\Liu80\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1181, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\Liu80\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 206, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 1005] 此卷不包含可识别的文件系统。
请确定所有请求的文件系统驱动程序已加载，且此卷未损坏。: 'H:\\115'`
115网盘本地已经挂载到了：
![image](https://github.com/CineMingle/CineMingle/assets/87924715/b3eabaa1-18c7-4195-bbd8-88df8a6cbdac)

**Comment by milanxiaotiejiang1** [comment]
已经解决了，挂载为网络盘就好了

**Comment by milanxiaotiejiang1** [comment]
如果挂载为本地盘就会有这个错误信息，挂载为网络盘在软链接那里会报错，错误信息为：
Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 805, in <module>
    main(args)
  File "Movie_Data_Capture.py", line 726, in main
    create_data_and_move(movie_path, zero_op, no_net_op, oCC)
  File "Movie_Data_Capture.py", line 526, in create_data_and_move
    core_main(movie_path, n_number, oCC)
  File "E:\CineMingle\core.py", line 958, in core_main
    paste_file_to_folder(movie_path, path, multi_part, number, part, leak_word, c_word, hack_word)
  File "E:\CineMingle\core.py", line 610, in paste_file_to_folder
    filerelpath = os.path.relpath(filepath, path)
  File "C:\Users\Liu80\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount '\\\\CloudDirve\\115', start on mount 'E:'

**Comment by CineMingle** [comment]
可以试一下重新安装 https://github.com/CineMingle/CineMingle/releases/tag/1.2.0

我刚刚修了一下：https://github.com/CineMingle/CineMingle/commit/25bb0232a7bfaac91f2815c45b86a9fce640d257

**Comment by milanxiaotiejiang1** [comment]
这个问题解决了，但是出现了新的错误：
`Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 805, in <module>
    main(args)
  File "Movie_Data_Capture.py", line 726, in main
    create_data_and_move(movie_path, zero_op, no_net_op, oCC)
  File "Movie_Data_Capture.py", line 526, in create_data_and_move
    core_main(movie_path, n_number, oCC)
  File "E:\CineMingle\core.py", line 958, in core_main
    paste_file_to_folder(movie_path, path, multi_part, number, part, leak_word, c_word, hack_word)
  File "E:\CineMingle\core.py", line 610, in paste_file_to_folder
    filerelpath = os.path.relpath(filepath, path)
  File "C:\Users\Liu80\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'H:', start on mount 'E:'`
这似乎是软链接在不同盘符中出现的错误

**Comment by milanxiaotiejiang1** [comment]
刚刚的错误解决了，但是出现了新的错误
`[+] ------- DEBUG INFO -------
[-]OS Error errno 22
[+]Add Mark:         字幕
[+]Wrote!            JAV_output\新村あかり\VEC-600\VEC-600-C.nfo
[*]======================================================
[!]                - 66.6% [2/3] -             17:43:22
[+]Skipping file:H:\115\VEC-600-C\x u u 6 2 . c o m.mp4
[!]                - 100.% [3/3] -             17:43:27
[+]Skipping file:H:\115\VEC-600-C\社 區 最 新 情 報.mp4
[+]Running time 0:00:16.274  End at 2024-01-14 17:43:30
[+]All finished!!!`
去除一些try代码，显示错误信息为：
`[+]Image Downloaded! thumb.jpg
[+]Image Cutted!     poster.jpg
Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 806, in <module>
    main(args)
  File "Movie_Data_Capture.py", line 727, in main
    create_data_and_move(movie_path, zero_op, no_net_op, oCC)
  File "Movie_Data_Capture.py", line 527, in create_data_and_move
    core_main(movie_path, n_number, oCC)
  File "E:\CineMingle\core.py", line 955, in core_main
    paste_file_to_folder(movie_path, path, multi_part, number, part, leak_word, c_word, hack_word)
  File "E:\CineMingle\core.py", line 607, in paste_file_to_folder
    filerelpath = os.path.relpath(filepath, path)
  File "C:\Users\Liu80\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'H:', start on mount 'E:'`

似乎是软连接出现了异常错误信息？

**Comment by milanxiaotiejiang1** [comment]
刚刚的问题解决了，但是又遇到了其他错误，去除一些try代码过后，错误信息为
```
Traceback (most recent call last):
  File "E:\CineMingle\core.py", line 607, in paste_file_to_folder
    filerelpath = os.path.relpath(filepath, path)
  File "C:\Users\Liu80\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'H:', start on mount 'E:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Movie_Data_Capture.py", line 806, in <module>
    main(args)
  File "Movie_Data_Capture.py", line 727, in main
    create_data_and_move(movie_path, zero_op, no_net_op, oCC)
  File "Movie_Data_Capture.py", line 527, in create_data_and_move
    core_main(movie_path, n_number, oCC)
  File "E:\CineMingle\core.py", line 955, in core_main
    paste_file_to_folder(movie_path, path, multi_part, number, part, leak_word, c_word, hack_word)
  File "E:\CineMingle\core.py", line 610, in paste_file_to_folder
    os.symlink(str(filepath_obj), targetpath)
OSError: [WinError 1314] 客户端没有所需的特权。: 'H:\\115\\VEC-600-C\\VEC-600-C.mp4' -> 'JAV_output\\新村あかり\\VEC-600
```

**Comment by milanxiaotiejiang1** [comment]
管理员运行就可以了，问题解决，感谢！

**Comment by milanxiaotiejiang1** [comment]
管理员运行就可以了，问题解决，感谢！
